@startuml

left to right direction
skinparam packageStyle rectangle

actor User as user << Human >>
database Database as database

rectangle "MBT Bundle" {
  user --> (log in)
  user --> (log out)
  user --> (register)
  (register) --> database
}

@enduml
