@startuml

actor User as user << Human >>
participant "MBT Bundle" as bundle
database Database as database
entity Queue as queue

user -> bundle : Bulk report bugs (bulk reduce bugs)
activate bundle
bundle -> queue : Create queue items
activate queue
queue --> bundle
deactivate queue
bundle --> user : Number of bugs queued
deactivate bundle

user -> bundle : Edit bug
activate bundle
bundle -> database : Store bug
activate database
database --> bundle
deactivate database
bundle -> database : Get bug
activate database
database --> bundle : Bug details
deactivate database
bundle --> user : Bug details
deactivate bundle

user -> bundle : View bug
activate bundle
bundle -> database : Get bug
activate database
database --> bundle : Bug details
deactivate database
bundle --> user : Bug details
deactivate bundle

user -> bundle : View bugs
activate bundle
bundle -> database : Get bugs
activate database
database --> bundle : Bug list
deactivate database
bundle --> user : Bug list
deactivate bundle

@enduml
