@startuml

left to right direction
skinparam packageStyle rectangle

actor Tester as tester << Human >>
database Database as database
entity Queue as queue

rectangle "MBT Bundle" {
  tester --> (bulk report bugs)
  tester --> (bulk reduce replays)
  tester --> (edit bug)
  tester --> (view bug)
  tester --> (view bugs)
  (bulk report bugs) --> queue
  (bulk reduce replays) --> queue
  (edit bug) --> database
  (view bug) --> database
  (view bugs) --> database
}

@enduml
