@startuml

left to right direction
skinparam packageStyle rectangle

actor User as user << Human >>
database Database as database
entity Queue as queue

rectangle "MBT Bundle" {
  user --> (bulk report bugs)
  user --> (bulk reduce replays)
  user --> (edit bug)
  user --> (view bug)
  user --> (view bugs)
  (bulk report bugs) --> queue
  (bulk reduce replays) --> queue
  (edit bug) --> database
  (view bug) --> database
  (view bugs) --> database
}

@enduml
