@startuml

actor User as user << Human >>
participant "MBT Bundle" as bundle
database Database as database

user -> bundle : View models
activate bundle
bundle -> database : Get models
activate database
database --> bundle : Model list
deactivate database
bundle --> user : Model list
deactivate bundle

@enduml
